//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.Product_Materials = new HashSet<Product_Materials>();
        }
    
        public int IdMaterials { get; set; }
        public string NameMaterials { get; set; }
        public Nullable<int> IdTypeMaterials { get; set; }
        public Nullable<int> NumberPackage { get; set; }
        public Nullable<int> IdUnitMeasurement { get; set; }
        public Nullable<int> NumberWarehouse { get; set; }
        public Nullable<int> MinimumBalance { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual TypeMaterials TypeMaterials { get; set; }
        public virtual UnitMeasurement UnitMeasurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Materials> Product_Materials { get; set; }
    }
}
