//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Materials
    {
        public int IdProductMaterials { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> IdMaterials { get; set; }
        public Nullable<int> NumberMaterials { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Product Product { get; set; }
    }
}
