//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_Materials = new HashSet<Product_Materials>();
        }
    
        public int IdProduct { get; set; }
        public string NameProduct { get; set; }
        public Nullable<int> ArticleNumber { get; set; }
        public Nullable<int> MinimumСost { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> IdTypeProduct { get; set; }
        public Nullable<int> NumberPeople { get; set; }
        public Nullable<int> NumberWorkshop { get; set; }
        public byte[] PhotoBinary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Materials> Product_Materials { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
